CREATE TABLE "GCG_6446_ROUTER_LINES" PAGESIZE=4096 (
 "ROUTER" CHAR(50),
 "SEQ" CHAR(50),
 "WORKCENTER_PART" CHAR(50),
 "OP_CODE" CHAR(50),
 "WC_DESC" CHAR(50),
 "WC_FACTOR" CHAR(50),
 "RUNTIME" CHAR(50),
 "RATE" CHAR(50),
 "PROJECT_GROUP" CHAR(50),
 "GS_USER" CHAR(50),
 "LMO" CHAR(1),
 "OMIT_FROM_WO" CHAR(1) );
